[package]
org = "ballerinax"
name = "confluent.cregistry"
version = "0.4.0"
authors = ["Ballerina"]
export=["confluent.cregistry"]
keywords = ["confluent", "schema_registry", "avro", "serdes"]
repository = "https://github.com/ballerina-platform/module-ballerinax-confluent.cregistry"
license = ["Apache-2.0"]
distribution = "2201.11.0-20241218-101200-109f6cc7"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "schema-registry-native"
version = "0.4.0"
path = "../native/build/libs/confluent.cregistry-native-0.4.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.confluent"
artifactId = "kafka-schema-registry-client"
version = "7.8.0"
path = "./lib/kafka-schema-registry-client-7.8.0.jar"

[[platform.java21.dependency]]
groupId = "io.confluent"
artifactId = "common-config"
version = "7.8.0"
path = "./lib/common-config-7.8.0.jar"

[[platform.java21.dependency]]
groupId = "io.confluent"
artifactId = "common-utils"
version = "7.8.0"
path = "./lib/common-utils-7.8.0.jar"

[[platform.java21.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "3.7.2"
path = "./lib/kafka-clients-3.7.2.jar"

[[platform.java21.dependency]]
groupId = "org.apache.avro"
artifactId = "avro"
version = "1.11.4"
path = "./lib/avro-1.11.4.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.18.1"
path = "./lib/jackson-core-2.18.1.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.18.1"
path = "./lib/jackson-annotations-2.18.1.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.18.1"
path = "./lib/jackson-databind-2.18.1.jar"

[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "32.0.1-jre"
path = "./lib/guava-32.0.1-jre.jar"
