[package]
org = "ballerinax"
name = "confluent.cregistry"
version = "0.1.2"
authors = ["Ballerina"]
export=["confluent.cregistry"]
keywords = ["confluent", "schema_registry", "avro", "serdes"]
repository = "https://github.com/ballerina-platform/module-ballerinax-confluent.cregistry"
license = ["Apache-2.0"]
distribution = "2201.8.6"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "schema-registry-native"
version = "0.1.2"
path = "../native/build/libs/confluent.cregistry-native-0.1.2-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.confluent"
artifactId = "kafka-schema-registry-client"
version = "5.3.2"
path = "./lib/kafka-schema-registry-client-5.3.2.jar"

[[platform.java17.dependency]]
groupId = "io.confluent"
artifactId = "common-config"
version = "5.3.0"
path = "./lib/common-config-5.3.0.jar"

[[platform.java17.dependency]]
groupId = "io.confluent"
artifactId = "common-utils"
version = "5.3.0"
path = "./lib/common-utils-5.3.0.jar"

[[platform.java17.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "3.7.0"
path = "./lib/kafka-clients-3.7.0.jar"

[[platform.java17.dependency]]
groupId = "org.apache.avro"
artifactId = "avro"
version = "1.11.3"
path = "./lib/avro-1.11.3.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.17.0"
path = "./lib/jackson-core-2.17.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.17.0"
path = "./lib/jackson-annotations-2.17.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.17.0"
path = "./lib/jackson-databind-2.17.0.jar"
